version: "3.9"
services:
  db:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=store-app
      - POSTGRES_PASSWORD=store-app
      - POSTGRES_DB=store-app

  api:
    build: .
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8004
    ports:
      - 8004:5000
    volumes:
      - .:/code 
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://store-app:shelter-app@db:5432/store-app
