version: "3.9"
services:
  db:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=store-app
      - POSTGRES_PASSWORD=store-app
      - POSTGRES_DB=store-app

  store-app:
    container_name: store-app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env.local
    ports:
      - 8004:5000
    depends_on:
      - services-app-db
    restart: on-failureapp
